[formatter.json]
command = "prettier"
options = ["-w"]
includes = ["*.json"]
excludes = []

[formatter.yaml]
command = "yamlfmt"
options = []
includes = ["*.yaml", "*.yml", ".yamlfmt"]
excludes = []

[formatter.dockerfmt]
command = "dockerfmt"
options = ["-n", "-w"]
includes = ["**/Dockerfile"]
excludes = []

[formatter.shfmt]
command = "shfmt"
options = ["-w"]
includes = ["*.sh"]
excludes = []

[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]
excludes = []

[formatter.go]
command = "gofmt"
options = ["-w"]
includes = ["*.go"]
excludes = []
